In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedShuffleSplit

In [2]:
ctrain=pd.read_csv(r'D:\Python new\PYTHON\PROJECT\PROJECT 2\carvan_train.csv')

In [3]:
ctest=pd.read_csv(r'D:\Python new\PYTHON\PROJECT\PROJECT 2\carvan_test.csv')

In [4]:
ctrain["data"]='train'
ctest['data']='test'

In [5]:
ctest['V86']=None

In [6]:
ctrain

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  ...  V78  V79  V80  V81  V82  \
0     33   1   3   2   8   0   5   1   3    7  ...    0    0    1    0    0   
1     37   1   2   2   8   1   4   1   4    6  ...    0    0    1    0    0   
2     37   1   2   2   8   0   4   2   4    3  ...    0    0    1    0    0   
3      9   1   3   3   3   2   3   2   4    5  ...    0    0    1    0    0   
4     40   1   4   2  10   1   4   1   4    7  ...    0    0    1    0    0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
5817  36   1   1   2   8   0   6   1   2    1  ...    0    0    1    0    0   
5818  35   1   4   4   8   1   4   1   4    6  ...    0    0    1    0    0   
5819  33   1   3   4   8   0   6   0   3    5  ...    0    0    1    0    0   
5820  34   1   3   2   8   0   7   0   2    7  ...    0    0    0    0    0   
5821  33   1   3   3   8   0   6   1   2    7  ...    0    0    0    0    0   

      V83  V84  V85  V86   data  
0       0    0    0    0  train  
1       0    0    0    0  train  
2       0    0    0    0  train  
3       0    0    0    0  train  
4       0    0    0    0  train  
...   ...  ...  ...  ...    ...  
5817    0    0    0    0  train  
5818    0    0    0    0  train  
5819    0    0    0    1  train  
5820    0    0    0    0  train  
5821    0    0    0    0  train  

[5822 rows x 87 columns]

In [7]:
ctrain.shape

(5822, 87)

In [8]:
c=pd.concat([ctrain,ctest],0)

In [9]:
c.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85', 'V86', 'data'],
      dtype='object')

In [10]:
c.shape

(9822, 87)

In [11]:
#pd.options.display.max_columns=90

In [12]:
#pd.options.display.min_rows=110

In [13]:
#pd.options.display.max_rows=110

In [14]:
c.dtypes

V1       int64
V2       int64
V3       int64
V4       int64
V5       int64
         ...  
V83      int64
V84      int64
V85      int64
V86     object
data    object
Length: 87, dtype: object

In [15]:
c["V86"].value_counts()

0    5474
1     348
Name: V86, dtype: int64

In [16]:
c.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85', 'V86', 'data'],
      dtype='object')

In [17]:
[c[i].value_counts() for i in c.columns]

[33    1401
 38     569
 8      546
 39     542
 9      460
 3      433
 23     376
 36     373
 35     362
 41     355
 34     325
 24     324
 31     318
 13     302
 11     286
 10     271
 32     234
 37     233
 1      218
 6      209
 12     194
 30     190
 22     169
 2      148
 29     139
 40     137
 25     129
 4       90
 26      79
 27      77
 7       72
 5       70
 20      42
 28      41
 21      29
 18      27
 16      25
 17      13
 15       7
 19       7
 Name: V1, dtype: int64, 1     8915
 2      821
 3       64
 7        8
 4        4
 6        3
 5        3
 10       2
 8        2
 Name: V2, dtype: int64, 3    4513
 2    3616
 4    1132
 1     452
 5     106
 6       3
 Name: V3, dtype: int64, 3    5154
 2    2409
 4    1777
 5     329
 1     104
 6      49
 Name: V4, dtype: int64, 8     2694
 3     1513
 9     1111
 1      959
 5      940
 7      881
 2      827
 10     492
 6      326
 4       79
 Name: V5, dtype: int64, 0    5420
 1    2744
 2    1213
 3     

In [18]:
cols=list(c.columns)
not_c = ['V4','V5','V6','V1','V44']

In [19]:
def Dummies(data,freq_n):
    for i in cols :
        if i in not_c:
            #print(i)
            freq=c[i].value_counts()
            Cate=freq.index[freq > freq_n] 
            #print(Cate)
            for cat in Cate:
                #print(cat)
                name = str(i)+'_'+str(cat)
               # print(name)
                data[name]= (data[str(i)]==cat).astype(int)
                #print(data[name])
            del data[str(i)]
    return data

In [20]:
Dummies(c,200)
c

V2  V3  V7  V8  V9  V10  V11  V12  V13  V14  ...  V5_2  V5_10  V5_6  \
0      1   3   5   1   3    7    0    2    1    2  ...     0      0     0   
1      1   2   4   1   4    6    2    2    0    4  ...     0      0     0   
2      1   2   4   2   4    3    2    4    4    4  ...     0      0     0   
3      1   3   3   2   4    5    2    2    2    3  ...     0      0     0   
4      1   4   4   1   4    7    1    2    2    4  ...     0      1     0   
...   ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   ...    ...   ...   
3995   1   2   7   2   0    5    2    2    2    6  ...     0      0     0   
3996   1   2   5   1   3    4    2    4    4    4  ...     0      0     0   
3997   1   2   5   1   3    7    0    2    2    5  ...     0      0     0   
3998   1   3   4   2   3    7    1    2    2    3  ...     0      0     0   
3999   1   2   3   0   3    5    2    2    0    6  ...     1      0     0   

      V6_0  V6_1  V6_2  V6_3  V44_0  V44_2  V44_1  
0        1     0     0     0      1      0      0  
1        0     1     0     0      0      1      0  
2        1     0     0     0      0      1      0  
3        0     0     1     0      1      0      0  
4        0     1     0     0      1      0      0  
...    ...   ...   ...   ...    ...    ...    ...  
3995     1     0     0     0      0      1      0  
3996     0     1     0     0      1      0      0  
3997     0     1     0     0      1      0      0  
3998     0     1     0     0      1      0      0  
3999     0     0     0     0      0      1      0  

[9822 rows x 122 columns]

In [21]:
c.isna().sum()

V2       0
V3       0
V7       0
V8       0
V9       0
        ..
V6_2     0
V6_3     0
V44_0    0
V44_2    0
V44_1    0
Length: 122, dtype: int64

In [22]:
train_data=c[c["data"]=='train']
test_data=c[c["data"]=='test']

In [23]:
Y_train=train_data['V86']

In [24]:
Y_train

0       0
1       0
2       0
3       0
4       0
       ..
5817    0
5818    0
5819    1
5820    0
5821    0
Name: V86, Length: 5822, dtype: object

In [25]:
X_train=train_data.drop(['data','V86'],1)
X_test=test_data.drop(['data','V86'],1)

In [26]:
X_train.shape

(5822, 120)

In [27]:
X_test.shape

(4000, 120)

In [28]:
Y_train

0       0
1       0
2       0
3       0
4       0
       ..
5817    0
5818    0
5819    1
5820    0
5821    0
Name: V86, Length: 5822, dtype: object

In [29]:
#This is for for balanced 1's &0's in test and train data to avoid over and underfitting
#stratifiedShufflesplit is used for this .

In [30]:
SSS=StratifiedShuffleSplit(n_splits=1,random_state=0,test_size=0.2)

In [31]:
SSS.get_n_splits(X_train)

1

In [32]:
print(SSS)

StratifiedShuffleSplit(n_splits=1, random_state=0, test_size=0.2,
            train_size=None)


In [33]:
Y_train.dtype

dtype('O')

In [34]:
Y_train=Y_train.astype(int)

In [35]:
for train_index,test_index in SSS.split(X_train,Y_train):
    print(train_index)
    print(test_index)

[1059 3195 5442 ...  964 1101 1889]
[3735 5576 3674 ... 5174   86  500]


In [36]:
x_train=X_train.loc[train_index]

In [37]:
x_train.shape

(4657, 120)

In [38]:
x_valid=X_train.loc[test_index]

In [39]:
x_valid.shape

(1165, 120)

In [40]:
y_train=Y_train.loc[train_index]

In [41]:
y_train.shape

(4657,)

In [42]:
y_train.value_counts()

0    4379
1     278
Name: V86, dtype: int64

In [43]:
y_valid=Y_train.loc[test_index]

In [44]:
y_valid.shape

(1165,)

In [45]:
y_valid.value_counts()

0    1095
1      70
Name: V86, dtype: int64

In [46]:
4379+278

4657

In [47]:
278/4657

0.05969508267124758

In [48]:
70/1165

0.060085836909871244

In [49]:
logr=LogisticRegression(class_weight="balanced",random_state= 3)

In [50]:
logr.fit(x_train,y_train)

D:\Python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=3, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [51]:
y_pred=logr.predict(x_valid)

In [52]:
roc_auc_score(y_valid,y_pred)

0.6169602087410306

In [53]:
#who

In [54]:
prob_score=pd.Series(list(zip(*logr.predict_proba(X_train)))[1])

In [55]:
prob_score.shape

(5822,)

In [56]:
#  * in above is used for bind all 1st columns in a list . list(zip(*logr.predict_proba(x_train)))[1]

In [57]:
cutoffs=np.linspace(0.010,0.99,100)
def Fbeta_perf(beta,cutoffs,y_train,prob_score):
    FB_cut=[]
    for cutoff in cutoffs:
        predicted=pd.Series([0]*len(y_train))
        predicted[prob_score>cutoff]=1
        df=pd.DataFrame(list(zip(y_train,predicted)),columns=["real","predicted"])

        TP=len(df[(df["real"]==1) &(df["predicted"]==1) ])
        FP=len(df[(df["real"]==0) &(df["predicted"]==1) ])
        FN=len(df[(df["real"]==1) &(df["predicted"]==0) ])
        P=TP+FN
        
        
        Precision=TP/(TP+FP)
        Recall=TP/P
        FB=(1+beta**2)*Precision*Recall/((beta**2)*Precision+Recall)
        FB_cut.append(FB)

    cutoff_data=pd.DataFrame(list(zip(cutoffs,FB_cut)),columns=["cutoff","FB"])

    FB_cutoff=cutoff_data[cutoff_data["FB"]==cutoff_data["FB"].max()]["cutoff"]

    prob_score_test=pd.Series(list(zip(*logr.predict_proba(x_valid)))[1])

    predicted_test=pd.Series([0]*len(y_valid))
    predicted_test[prob_score_test>float(FB_cutoff)]=1

    df_test=pd.DataFrame(list(zip(y_valid,predicted_test)),columns=["real","predicted"])

    k=pd.crosstab(df_test['real'],df_test["predicted"])
#     print('confusion matrix :\n \n ',k)
    TN=k.iloc[0,0]
    TP=k.iloc[1,1]
    FP=k.iloc[0,1]
    FN=k.iloc[1,0]
    P=TP+FN
    N=TN+FP
    Precision=TP/(TP+FP)
    Recall=TP/P
    FB=(1+beta**2)*Precision*Recall/((beta**2)*Precision+Recall)
            
    print('For beta :',beta)
    print('Accuracy is :',(TP+TN)/(P+N))
    print('Sensitivity is :',(TP/P))
    print('Specificity is :',(TN/N))
    print("precision:",TP/(TP+FP))
    print('fb score:',FB)
    print('\n \n \n')
    

In [58]:
s=pd.crosstab(y_valid,y_pred)

In [59]:
s

col_0    0    1
V86            
0      788  307
1       34   36

In [60]:
s.iloc[0,0]

788

In [61]:
s.iloc[1,1]

36

In [62]:
Fbeta_perf(0.5,cutoffs,Y_train,prob_score)
Fbeta_perf(1,cutoffs,Y_train,prob_score)
Fbeta_perf(2,cutoffs,Y_train,prob_score)

For beta : 0.5
Accuracy is : 0.9210300429184549
Sensitivity is : 0.1
Specificity is : 0.9735159817351599
precision: 0.19444444444444445
fb score: 0.16355140186915887

 
 

For beta : 1
Accuracy is : 0.8360515021459227
Sensitivity is : 0.3142857142857143
Specificity is : 0.869406392694064
precision: 0.13333333333333333
fb score: 0.1872340425531915

 
 

For beta : 2
Accuracy is : 0.6969957081545064
Sensitivity is : 0.5571428571428572
Specificity is : 0.7059360730593607
precision: 0.10803324099722991
fb score: 0.3042121684867395

 
 



In [63]:
RESULT=logr.predict(X_test)

In [64]:
RESULT.shape

(4000,)

In [65]:
np.unique(RESULT,return_counts=True)

(array([0, 1]), array([2753, 1247], dtype=int64))

In [66]:
1220/(2780+1220)

0.305

In [67]:
#result=pd.DataFrame(RESULT).to_csv('D:\Python new\PYTHON\PROJECT\PROJECT 2\RAHUL_SHEDGE_P2_part2.csv',index=False)

In [68]:
#result